# Generated by Django 5.2.4 on 2025-07-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet', '0002_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
